Fix issue #11.  At least in a narrow sense.
This is only part of the story, however.  We've still managed to introduce all the
following test failures with the new policy on treating unit arrays:

----------------------------------------

run test 12/67 p11:: [Failed]
ERROR: repackAcc2: ran out of input arrays.

run test 13/67 p11b:: [Failed]
ERROR: repackAcc2: ran out of input arrays.

run test 14/67 p11c:: [Failed]
ERROR: repackAcc2: ran out of input arrays.

----------------------------------------

run test 23/67 p13j:: [Failed]
ERROR: packArray: given a AccArray of the wrong type, expected Int received 2 payloads:
ArrayPayloadUnit 1
ArrayPayloadInt (array (0,0) [(0,-5764607523034234880)])

 dimension: []

----------------------------------------

run test 64/67 p5:: [Failed]
ERROR: packArray: given a AccArray of the wrong type, expected Int received 3 payloads:
ArrayPayloadUnit 1
ArrayPayloadInt (array (0,0) [(0,-6917529027641081856)])
ArrayPayloadUnit 1

----------------------------------------